on:
  push:
jobs:
  version_go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.17", "1.18", "1.19"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Test with Go
        run: go test ./...
      